---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch-logs
  labels:
    app.kubernetes.io/environment: ${label_environment}
    app.kubernetes.io/instance: elasticsearch-logs
    app.kubernetes.io/managed-by: Kustomization
    app.kubernetes.io/name: elasticsearch-logs
    app.kubernetes.io/repository: ${label_repository}
