---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-operator
  namespace: flux-system
namespace: elastic-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/name: elastic
      flux.kub3.uk/kustomization: elastic-operator
      flux.kub3.uk/application: elastic
      flux.kub3.uk/component: operator
      flux.kub3.uk/managed-by: kustomization

resources:
  - namespace.yaml
  - elastic-operator-helm.yaml

configMapGenerator:
  - name: helm-elastic-operator-values
    files:
      - values.yaml=elastic-operator-values.yaml

configurations:
  - kustomize-config.yaml
