---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: node-exporter
  namespace: flux-system
namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: node-exporter
      flux.kub3.uk/name: prometheus
      flux.kub3.uk/application: node-exporter
      flux.kub3.uk/component: metrics
      flux.kub3.uk/managed-by: kustomization

resources:
  - node-exporter-helm.yaml

configMapGenerator:
  - name: helm-node-exporter-values
    files:
      - values.yaml=node-exporter-values.yaml

configurations:
  - kustomize-config.yaml
