---
fullnameOverride: node-exporter

prometheus:
  monitor:
    enabled: true

networkPolicy:
  enabled: false

resources:
  limits: # Don't limit the CPU
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi
