---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller-charts
spec:
  secretRef:
    name: ghcr-login
  provider: generic
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  interval: 24h
