---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: traefik
spec:
  secretRef:
    name: ghcr-login
  provider: generic
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    semver: 35.0.1
