---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: certificates
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
      - kind: Secret
        name: cert-manager-substitutions
