---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-dns
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: core-dns
  interval: 1h
  retryInterval: 10m
  prune: true
