---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-operator
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: elastic-operator
  dependsOn:
    - name: sources
    - name: elastic-crds
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
