---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-logs
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: elastic-logs
  dependsOn:
    - name: elastic-operator
    - name: proxmox-csi
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
