---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: flux
  dependsOn:
    - name: sources
    - name: cert-manager-crds
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
