---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: grafana
  dependsOn:
    - name: prometheus-crds
    - name: proxmox-csi
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
