---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-haproxy
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: ingress-haproxy
  dependsOn:
    - name: sources
    - name: prometheus-crds
    - name: cert-manager-crds
    # We need the ingress-system Namespace
    - name: ingress-nginx
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
