---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: keda
  dependsOn:
    - name: sources
    - name: cert-manager-crds
    - name: prometheus-crds
    - name: keda-crds
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
