---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
namespace: flux-system

resources:
  - sources.yaml
  - custom-resources.yaml
  - flux.yaml
  - core-dns.yaml
  - proxmox-csi.yaml
  - metrics-server.yaml
  - cloudflared.yaml
  - cert-manager.yaml
  - certificates.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - routing.yaml
  - elastic-operator.yaml
  - prometheus.yaml
  - elastic-logs.yaml
  - fluent-bit.yaml
  - alertmanager.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - keda.yaml
  - grafana.yaml
  - podinfo.yaml
