---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: podinfo
  dependsOn:
    - name: sources
    - name: prometheus-crds
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
