---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routing
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: routing
  dependsOn:
    - name: metallb
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
      - kind: ConfigMap
        name: routing-substitutions
