---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: tailscale-crds
  dependsOn:
    - name: sources
  interval: 1h
  retryInterval: 10m
  prune: true
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: tailscale-operator
  dependsOn:
    - name: sources
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
      - kind: ConfigMap
        name: tailscale-substitutions
