---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: trivy-operator
  dependsOn:
    - name: sources
    - name: prometheus-crds
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
      - kind: Secret
        name: trivy-operator-substitutions
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trivy-operator-dashboard
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: baseline
  path: trivy-operator-dashboard
  dependsOn:
    - name: sources
    - name: gateways
    - name: trivy-operator
  interval: 1h
  retryInterval: 10m
  prune: true

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-substitutions
      - kind: Secret
        name: trivy-operator-dashboard-substitutions
