---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: 18:00
      timezone: Europe/London
    commit-message:
      prefix: actions
      include: scope
    labels:
      - type/dependencies
      - update/github-workflows
      - release/chore

  - package-ecosystem: terraform
    directory: terraform/
    schedule:
      interval: daily
      time: 18:30
      timezone: Europe/London
    commit-message:
      prefix: terraform
      include: scope
    labels:
      - type/dependencies
      - update/terraform
      - release/chore
