---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://github.com/Mergifyio/docs/raw/refs/heads/main/public/mergify-configuration-schema.json

# When working with Dependabot and GitHub Actions, where those Actions can make
# changes to documentation or code based on updates to the repository's
# dependencies, it is normally safe to automatically approve and merge these
# changes so long as the integrations are successful.

pull_request_rules:
  - name: Automatic approval for Dependabot pull requests
    # If the pull request was raised by Dependabot, and only Dependabot or
    # GitHub Actions have made changes to the branch, then automatically approve
    # if it's not in conflict with the base branch, and not closed
    conditions:
      - 'author=dependabot[bot]'
      - 'base=main'
      - '#commits-behind=0'
      - '-conflict'
      - '-closed'
      - or:
          - 'commits[*].author==dependabot[bot]'
          - 'commits[*].author==github-actions[bot]'
    actions:
      review:
        type: APPROVE

  - name: Automatic merge for Dependabot pull requests
    # If the pull request was raised by Dependabot, it only has a linear
    # history, it has been approved for merging into the main or master
    # branches, and is neither in conflict with the main branch, nor fallen
    # behind, then automatically merge this request
    conditions:
      - 'author=dependabot[bot]'
      - 'base=main'
      - 'linear-history'
      - '#approved-reviews-by>=1'
      - '-conflict'
      - '-closed'
    actions:
      merge:
        method: merge
