---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: approver-policy
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jetstack
      chart: cert-manager-approver-policy
      interval: 5m
      version: 0.16.0
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  dependsOn:
    - name: cert-manager

  valuesFrom:
    - kind: ConfigMap
      name: helm-approver-policy-values
