---
extends: default

ignore:
  - flux/prometheus-crds/resources.yaml
  - flux/cert-manager-crds/resources.yaml
  - flux/elastic-crds/resources.yaml
  - flux/elastic-crds/operator.yaml
  - flux/grafana-crds/resources.yaml

rules:
  document-start:
    present: true
  document-end:
    present: false

  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: {}

  indentation:
    spaces: consistent
    indent-sequences: true
    # Taskfiles use variable indentations on multi-line strings for the
    # documentation and in-line scripting
    check-multi-line-strings: false

  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  brackets:
    forbid: non-empty

  braces:
    forbid: non-empty

  float-values:
    forbid-nan: true
    require-numeral-before-decimal: true

  quoted-strings:
    quote-type: single
    required: only-when-needed
    allow-quoted-quotes: true

  trailing-spaces: {}

  truthy:
    allowed-values:
      - 'true'
      - 'false'
    check-keys: false
