---
fullnameOverride: external

controller:
  image:
    readOnlyRootFilesystem: false
  ingressClassResource:
    name: external
    default: false
  ingressClass: external

  kind: Deployment
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  replicaCount: 3
  minAvailable: 2

  resources:
    limits: # Don't limit the CPU
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: external
          app.kubernetes.io/component: controller
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: external
          app.kubernetes.io/component: controller

  service:
    enabled: true
    external:
      enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    sessionAffinity: None

  opentelemetry:
    enabled: false

  # admissionWebhooks:
  #   certManager:
  #     enabled: true
  #     rootCert:
  #       duration: 43800h # 5y
  #     admissionCert:
  #       duration: 2184h # 13w
  #       issuerRef:
  #         kind: ClusterIssuer
  #         name: ingress-nginx

  metrics:
    port: 10254
    portName: metrics
    enabled: true
    serviceMonitor:
      enabled: true

defaultBackend:
  enabled: true
  name: default-backend

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  replicaCount: 2
  minAvailable: 1
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: default-backend
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: default-backend
