---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-rules
  namespace: flux-system
namespace: prometheus-metrics

commonLabels:
  flux.kub3.uk/organisation: n3tuk
  flux.kub3.uk/repository: infra-flux
  flux.kub3.uk/kustomization: prometheus-rules
  flux.kub3.uk/application: prometheus
  flux.kub3.uk/component: rules

resources:
  - general.yaml
  - kubernetes.yaml
  - nodes.yaml
  - workloads.yaml
  - persistent-volumes.yaml
  - prometheus.yaml
  - alertmanager.yaml
