---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grfana-operator
namespace: grafana-operator

commonLabels:
  flux.kub3.uk/organisation: n3tuk
  flux.kub3.uk/repository: infra-flux
  flux.kub3.uk/kustomization: grafana-crds
  flux.kub3.uk/name: grafana-operator
  flux.kub3.uk/application: grafana
  flux.kub3.uk/component: grafana-operator
  flux.kub3.uk/managed-by: kustomization

resources:
  - namespace.yaml
  - resources.yaml
