---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema= https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  labels:
    app.kubernetes.io/managed-by: Kustomization
stringData:
  api-token: ${cloudflare_api_token}
