---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
namespace: dns-system

commonLabels:
  flux.kub3.uk/component: cloudflare

resources:
  - cloudflare-helm.yaml
  - cloudflare-secrets.yaml

configMapGenerator:
  - name: helm-cloudflare-values
    files:
      - values.yaml=cloudflare-values.yaml

configurations:
  - kustomize-config.yaml
