---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/monitoring.coreos.com/prometheus_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: metrics
  namespace: prometheus-metrics
  labels:
    prometheus: metrics
spec:
  image: quay.io/prometheus/prometheus:v3.2.0
  version: v3.2.0

  externalUrl: https://prometheus.${cluster_domain}/

  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  shards: 1

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          prometheus: metrics
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          prometheus: metrics

  enableFeatures:
    - memory-snapshot-on-shutdown

  serviceAccountName: prometheus

  retention: 2160h
  retentionSize: 112GiB
  disableCompaction: true
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: proxmox-rbd-ext4
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi

  resources:
    limits: # Don't limit the CPU
      memory: 1434Mi
    requests:
      cpu: 75m
      memory: 1228Mi

  logFormat: json

  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  scrapeInterval: 15s

  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}

  probeSelector: {}
  probeNamespaceSelector: {}

  scrapeConfigSelector: {}
  scrapeConfigNamespaceSelector: {}

  ruleSelector:
    matchLabels:
      alertmanager: metrics
  ruleNamespaceSelector: {}

  externalLabels:
    cluster: ${cluster}

  alerting:
    alertmanagers:
      - namespace: prometheus-metrics
        name: alertmanager-operated
        port: web
