---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus-metrics
  labels:
    prometheus: metrics
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: metrics
  sessionAffinity: ClientIP
