---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: prometheus-metrics
  labels:
    prometheus: metrics
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      prometheus: metrics
