---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-metrics
  namespace: prometheus-metrics
  labels:
    alertmanager: metrics
type: Opaque
stringData:
  alertmanager.yaml: |
    ---
    # Set a default, empty configuration with a "null" receiver which can be
    # expanded upon by the AlertmanagerConfig resources deployed
    global:
      resolve_timeout: 1m
      pagerduty_url: https://events.eu.pagerduty.com/v2/enqueue
    templates:
      - /etc/alertmanager/configmaps/alertmanager-templates/*.tmpl
    route:
      group_by:
        - cluster
        - namespace
        - alertname
      group_interval: 3m
      group_wait: 15s
      receiver: "null"
    receivers:
      - name: "null"
    inhibit_rules:
      - target_matchers:
          - ignore="always"
      - source_matchers:
          - alertname="OutsideWorkingHours"
        target_matchers:
          - ignore="outside-working-hours"
      - source_matchers:
          - alertname="OutsideExtendedHours"
        target_matchers:
          - ignore="outside-extended-hours"
      - source_matchers:
          - alertname="OutsideNonWorkingHours"
        target_matchers:
          - ignore="outside-non-working-hours"
      - source_matchers:
          - alertname="OutsideWeekendHours"
        target_matchers:
          - ignore="outside-weekend-hours"
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack
  labels:
    alertmanager: metrics
spec:
  route:
    receiver: slack
    matchers:
      - name: slack
        matchType: =~
        value: ^[a-z0-9._-]+$
      - name: slack
        matchType: '!='
        value: ignore
    repeatInterval: 3h
    continue: true

  receivers:
    - name: slack
      slackConfigs:
        - apiURL:
            name: slack-webhooks
            key: alerts
          httpConfig: {}
          channel: >-
            {{ template "slack.n3tuk.channel" . }}
          sendResolved: true
          shortFields: false
          iconEmoji: ':alertmanager:'
          iconURL: https://alerts.${cluster_domain}/
          color: >-
            {{ template "slack.n3tuk.color" . }}
          username: >-
            {{ template "slack.n3tuk.username" . }}
          title: >-
            {{ template "slack.n3tuk.title" . }}
          titleLink: >-
            {{ template "slack.n3tuk.link" . }}
          pretext: |
            {{ template "slack.n3tuk.pretext" .Alerts }}
          text: |
            {{ template "slack.n3tuk.text" . }}
          footer: |
            {{ template "slack.n3tuk.footer" . }}
          fallback: >-
            {{ template "slack.n3tuk.fallback" . }}
          fields:
            - title: Alert Name
              value: >-
                {{ .GroupLabels.alertname }}
              short: false
            - title: Cluster
              value: >-
                {{ template "slack.n3tuk.cluster" . }}
              short: true
            - title: Namespace
              value: >-
                {{ template "slack.n3tuk.namespace" . }}
              short: true
            - title: Severity
              value: >-
                {{ template "slack.n3tuk.severity" . }}
              short: true
            - title: Since
              value: >-
                {{ (index .Alerts 0).StartsAt | since | humanizeDuration }}
              short: true
          actions:
            - text: Runbook
              type: button
              url: >-
                {{ (index .Alerts 0).Annotations.runbook }}
            - text: Query
              type: button
              url: >-
                {{ (index .Alerts 0).GeneratorURL }}
            - text: Dashboard
              type: button
              url: >-
                {{ (index .Alerts 0).Annotations.dashboard }}
            - text: Silence
              type: button
              url: >-
                {{ template "__alert_silence_link" . }}
          linkNames: true
          mrkdwnIn:
            - title
            - pretext
            - text
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pagerduty
  labels:
    alertmanager: metrics
spec:
  route:
    receiver: pagerduty
    matchers:
      - name: pagerduty
        matchType: =~
        value: ^P[0-9]$
      - name: pagerduty
        matchType: '!='
        value: ignore
    repeatInterval: 15m
    continue: true

  receivers:
    - name: pagerduty
      pagerdutyConfigs:
        - serviceKey:
            name: pagerduty-keys
            key: service-key
          sendResolved: true
          client: >-
            {{ template "pagerduty.n3tuk.client" . }}
          clientURL: >-
            {{ template "pagerduty.n3tuk.client_url" . }}
          description: >-
            {{ template "pagerduty.n3tuk.title" . }}
          severity: >-
            {{ template "pagerduty.n3tuk.priority" . }}
          source: >-
            {{ template "pagerduty.n3tuk.username" . }}
          details:
            - key: alert name
              value: >-
                {{ template "pagerduty.n3tuk.alert_name" . }}
            - key: summary
              value: >-
                {{ template "pagerduty.n3tuk.summary" . }}
            - key: priority
              value: >-
                {{ template "pagerduty.n3tuk.priority" . }}
            - key: cluster
              value: >-
                {{ template "pagerduty.n3tuk.cluster" . }}
            - key: namespace
              value: >-
                {{ template "pagerduty.n3tuk.namespace" . }}
            - key: severity
              value: >-
                {{ template "pagerduty.n3tuk.severity" . }}
            - key: firing
              value: >-
                {{ template "pagerduty.n3tuk.firing" . }}
            - key: resolved
              value: >-
                {{ template "pagerduty.n3tuk.resolved" . }}
          pagerDutyLinkConfigs:
            - alt: Runbooks
              href: >-
                {{ template "pagerduty.n3tuk.runbook" . }}
            - alt: Dashboard
              href: >-
                {{ template "pagerduty.n3tuk.dashboard" . }}
            - alt: Prometheus
              href: >-
                {{ (index .Alerts 0).GeneratorURL }}
            - alt: Alertmanager
              href: >-
                https://alerts.${cluster_domain}/
            - alt: Silence
              href: >-
                {{ template "__alert_silence_link" . }}
          component: kub3-${cluster}
          group: ${cluster}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: incident-io
  labels:
    alertmanager: metrics
spec:
  route:
    receiver: incident.io
    matchers:
      - name: incident
        matchType: =~
        value: ^[a-z0-9._-]+$
      - name: incident
        matchType: '!='
        value: ignore
    repeatInterval: 1m
    continue: true

  receivers:
    - name: incident.io
      webhookConfigs:
        - url: >-
            https://api.incident.io/v2/alert_events/alertmanager/01JP5TDYDQTRJAKSTKSWC0X116
          sendResolved: true
          httpConfig:
            authorization:
              credentials:
                name: incidentio-credentials
                key: credentials
