---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema= https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-metrics
  namespace: prometheus-metrics
  labels:
    alertmanager: metrics
type: Opaque
stringData:
  alertmanager.yaml: |
    ---
    # Set a default, empty configuration with a "null" receiver which can be
    # expanded upon by the AlertmanagerConfig resources deployed
    global:
      resolve_timeout: 1m
      pagerduty_url: https://events.eu.pagerduty.com/v2/enqueue
    templates:
      - /etc/alertmanager/configmaps/alertmanager-templates/*.tmpl
    route:
      group_by:
        - cluster
        - namespace
        - alertname
      group_interval: 3m
      group_wait: 15s
      receiver: "null"
    receivers:
      - name: "null"
    inhibit_rules:
      - target_matchers:
          - ignore="always"
      - source_matchers:
          - alertname="OutsideWorkingHours"
        target_matchers:
          - ignore="outside-working-hours"
      - source_matchers:
          - alertname="OutsideExtendedHours"
        target_matchers:
          - ignore="outside-extended-hours"
      - source_matchers:
          - alertname="OutsideNonWorkingHours"
        target_matchers:
          - ignore="outside-non-working-hours"
      - source_matchers:
          - alertname="OutsideWeekendHours"
        target_matchers:
          - ignore="outside-weekend-hours"
