---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: alertmanager-metrics
  namespace: flux-system
namespace: prometheus-metrics

labels:
  - includeSelectors: false
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: alertmanager
      flux.kub3.uk/name: prometheus
      flux.kub3.uk/application: alertmanager
      flux.kub3.uk/component: metrics
      flux.kub3.uk/managed-by: kustomization

resources:
  - alertmanager.yaml
  - config.yaml
  - slack.yaml
  # - pagerduty.yaml
  - incidentio.yaml
  - service.yaml
  - service-monitor.yaml
  - ingress.yaml

configMapGenerator:
  - name: alertmanager-templates
    options:
      # Kustomize transformers cannot target items in lists for prefix and
      # suffix changes currently, so disable random suffixes on the ConfigMap
      #   https://github.com/kubernetes-sigs/kustomize/issues/4884
      disableNameSuffixHash: true
    files:
      - common.tmpl=common.tmpl
      - slack.tmpl=slack.tmpl
      - pagerduty.tmpl=pagerduty.tmpl
