---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pagerduty
  labels:
    alertmanager: metrics
spec:
  route:
    receiver: incidents
    matchers:
      - name: pagerduty
        matchType: =~
        value: ^[a-z0-9._-]+$
      - name: pagerduty
        matchType: '!='
        value: ignore
    repeatInterval: 15m
    continue: true

  receivers:
    - name: incidents
      pagerdutyConfigs:
        - serviceKey:
            name: pagerduty-keys
            key: service-key
          sendResolved: true
          client: >-
            {{ template "common.n3tuk.instance" . }}
          clientURL: >-
            {{ template "common.n3tuk.alertmanager_link" . }}
          description: >-
            {{ template "common.n3tuk.title" . }}
          severity: >-
            {{ template "common.n3tuk.severity" . }}
          source: >-
            {{ template "common.n3tuk.instance" . }}
          details:
            - key: alert name
              value: >-
                {{ template "common.n3tuk.alertname" . }}
            - key: summary
              value: >-
                {{ template "pagerduty.n3tuk.summary" . }}
            - key: cluster
              value: >-
                {{ template "common.n3tuk.cluster" . }}
            - key: namespace
              value: >-
                {{ template "common.n3tuk.namespace" . }}
            - key: severity
              value: >-
                {{ template "common.n3tuk.severity" . }}
            - key: firing
              value: >-
                {{ template "pagerduty.n3tuk.firing" . }}
            - key: resolved
              value: >-
                {{ template "pagerduty.n3tuk.resolved" . }}
          pagerDutyLinkConfigs:
            - alt: Prometheus Query
              href: >-
                {{ template "common.n3tuk.prometheus_query_link" . }}
            - alt: Prometheus Alerts
              href: >-
                {{ template "common.n3tuk.prometheus_alert_link" . }}
            - alt: Alertmanager Alerts
              href: >-
                {{ template "common.n3tuk.alertmanager_link" . }}
            - alt: Grafana Dashboard
              href: >-
                {{ template "common.n3tuk.dashboard" . }}
            - alt: Review the Runbook
              href: >-
                {{ template "common.n3tuk.runbook" . }}
            - alt: Silence this Alert
              href: >-
                {{ template "common.n3tuk.silence_single_link" . }}
            - alt: Silence all Alerts
              href: >-
                {{ template "common.n3tuk.silence_all_link" . }}
          component: kub3-${cluster}
          group: ${cluster}
