---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  labels:
    alertmanager: metrics
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      alertmanager: metrics
