---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus-metrics
  labels:
    alertmanager: metrics
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: metrics
  sessionAffinity: ClientIP
  internalTrafficPolicy: Cluster
