---
clusterName: ${cluster}

crds:
  install: false

operator:
  disableCompression: false

metricsServer:
  disableCompression: false

upgradeStrategy:
  operator:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1

  metricsApiServer:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1

  webhooks:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1

podDisruptionBudget:
  operator:
    minAvailable: 1

  metricServer:
    minAvailable: 1

  webhooks:
    minAvailable: 1

logging:
  operator:
    level: info
    format: json
    timeEncoding: rfc3339nano
  webhooks:
    level: info
    format: json
    timeEncoding: rfc3339nano

resources:
  operator:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  operator:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
  webhooks:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true

certificates:
  autoGenerated: true
  # -- Secret name to be mounted with KEDA TLS certificates
  secretName: keda-certificates
  # -- Path where KEDA TLS certificates are mounted
  mountPath: /certs
  certManager:
    enabled: true
    generateCA: true
    duration: 1008h # 6 weeks
    renewBefore: 672h # 4 weeks
    caSecretName: keda-certificate-authority
    issuer:
      generate: true
      name: keda-certificate-authority
      kind: ClusterIssuer
      group: cert-manager.io

enableServiceLinks: false
