---
apiVersion: v1
kind: Secret
metadata:
  name: helm-proxmox-csi-values
stringData:
  values.yaml: |-
    ---
    config:
      clusters:
        - url: ${proxmox_csi_url}
          token_id: ${proxmox_csi_token_id}
          token_secret: ${proxmox_csi_token_secret}
          region: ${proxmox_csi_region}
