---
fullnameOverride: haproxy-external
nameOverride: haproxy-external

controller:
  kind: Deployment
  replicaCount: 2

  config:
    scale-server-slots: '5'
    maxconn: '200'
    pod-maxconn: '20'
    hard-stop-after: 30s
    # yamllint disable rule:line-length
    global-config-snippet: |
      ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12
      ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
      tune.ssl.default-dh-param 4096
    # yamllint enable rule:line-length
    frontend-config-snippet: |
      option socket-stats
    log-format: >-
      %{+json}o
      %(time)Tl
      %(client-ip)ci
      %(client-port)cp
      %(frontend-name)ft
      %(backend-name)b
      %(server-name)s
      %(server-ip)si
      %(server-port)sp
      %(ssl-version)sslv
      %(ssl-cipher)sslc
      %(ssl-client-auth)[ssl_c_used]
      %(ssl-client-ca)[ssl_c_r_dn(CN)]
      %(ssl-client-cn)[ssl_c_s_dn(CN)]
      %(ssl-client-serial)[ssl_c_serial,hex]
      %(ssl-sni)[ssl_fc_sni]
      %(pod)H
      %(http-protocol)HV
      %(http-method)HM
      %(http-uri){+Q}HU
      %(http-status-code)ST
      %(bytes-in)U
      %(retries)rc
      %(bytes-out)B
      %(termination-state)ts

  logging:
    traffic:
      address: stdout
      format: raw
      facility: daemon

  service:
    enabled: true
    type: LoadBalancer

    metrics:
      type: ClusterIP
    enablePorts:
      admin: false

  ingressClassResource:
    name: haproxy-external
    default: false

  ingressClass: haproxy-external

  kubernetesGateway:
    enabled: true
    gatewayControllerName: haproxy.org/gateway-external

  resources:
    limits: # Don't limit the CPU
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi

  podDisruptionBudget:
    enable: true
    minAvailable: 1

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: haproxy-external
          app.kubernetes.io/instance: haproxy
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: haproxy-external
          app.kubernetes.io/instance: haproxy

  strategy:
    type: RollingUpdate
    maxUnavailable: 1

  serviceMonitor:
    enabled: true
    endpoints:
      - port: stat
        path: /metrics
        scheme: http
        interval: 30s
        params:
          no-maint:
            - empty
          extra-counters:
            - 'on'
