---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-crds
namespace: traefik-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: traefik-crds
      flux.kub3.uk/name: traefik
      flux.kub3.uk/application: traefik
      flux.kub3.uk/component: custom-resource-definitions
      flux.kub3.uk/managed-by: kustomization

resources:
  - namespace.yaml
  - resources.yaml
