---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: envoy
spec: {}
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: envoy
spec:
  type: ingress
  proxyClass: envoy
  hostnamePrefix: kub3-${cluster}-envoy
  replicas: 2
  tags:
    - tag:k8s-ingress
    - tag:k8s-${cluster}-ingress
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: haproxy
spec: {}
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: haproxy
spec:
  type: ingress
  proxyClass: haproxy
  hostnamePrefix: kub3-${cluster}-haproxy
  replicas: 2
  tags:
    - tag:k8s-ingress
    - tag:k8s-${cluster}-ingress
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: egress
spec: {}
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  proxyClass: egress
  hostnamePrefix: kub3-${cluster}-egress
  replicas: 2
  tags:
    - tag:k8s-egress
    - tag:k8s-${cluster}-egress
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: api-server
spec: {}
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: api-server
spec:
  type: kube-apiserver
  proxyClass: api-server
  kubeAPIServer:
    hostname: kub3-${cluster}-api-server
    mode: auth
  hostnamePrefix: kub3-${cluster}-api-server
  replicas: 2
  tags:
    - tag:k8s-api-server
    - tag:k8s-${cluster}-api-server
