{
 "title": "ElasticSearch Service",
 "description": "A multi-Kubernetes cluster and multi-ElasticSearch cluster dashboard are used to review the current operational state of ElasticSearch and its components.",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "production" },
   {
    "name": "esCluster",
    "label": "ElasticSearch Cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status{namespace=\"elastic-logs\"},cluster)"
    }
   },
   {
    "name": "esNode",
    "label": "ElasticSearch Node",
    "query": {
     "query": "label_values(elasticsearch_nodes_roles{namespace=\"elastic-logs\"},name)"
    }
   },
   {
    "name": "esIndex",
    "label": "Index",
    "query": {
     "query": "label_values(stream_date:elasticsearch_indices_docs_primary:sum{cluster=\"$esCluster\"},stream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ElasticSearch Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ElasticSearch Cluster Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(elasticsearch_cluster_health_status{cluster=\"$esCluster\",color=\"green\"} == 1) or (elasticsearch_cluster_health_status{cluster=\"$esCluster\",color=\"yellow\"} == 1)+1 or (elasticsearch_cluster_health_status{cluster=\"$esCluster\",color=\"red\"} == 1)+2",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(name) (elasticsearch_nodes_roles{cluster=\"$esCluster\"}))",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (elasticsearch_breakers_tripped{cluster=\"$esCluster\"})",
     "legendFormat": "Breakers Tripped"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, cluster) (stream_date:elasticsearch_indices_docs_primary:rate3m{cluster=\"$esCluster\",stream=~\"$esIndex\"})",
     "legendFormat": "Ingestion"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, cluster) (stream_date:elasticsearch_indices_docs_primary:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(name:elasticsearch_filesystem_data_size_bytes:capacity_by_top_indicies{cluster=\"$esCluster\"})",
     "legendFormat": "Log Capacity"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(name) (elasticsearch_nodes_roles{cluster=\"$esCluster\", role=\"data\"}))",
     "legendFormat": "Data Nodes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$esCluster\"})",
     "legendFormat": "Pending Tasks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count by (stream) (stream_date:elasticsearch_indices_docs_primary:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"}))",
     "legendFormat": "Log History"
    }
   ]
  },
  { "title": "Sharding Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Primary Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$esCluster\"} / on (namespace,cluster) (min by (namespace,cluster) (elasticsearch_jvm_memory_max_bytes{cluster=\"$esCluster\",es_master_node=\"true\",area=\"heap\"}) / (1024^3))",
     "legendFormat": "Shards per JVM GiB (Master) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$esCluster\"} - elasticsearch_cluster_health_active_primary_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Secondary Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Initilising Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Relocating Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Unassigned Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$esCluster\"}",
     "legendFormat": "Delayed Shards"
    }
   ]
  },
  { "title": "$esIndex Index Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "esIndex" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (stream) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stream) (rate(stream_date:elasticsearch_indices_docs_primary:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"}[3m]))",
     "legendFormat": "Ingestion Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stream) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"})",
     "legendFormat": "Total Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stream) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"}) / count by (stream) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\"})",
     "legendFormat": "Average Shard"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (stream) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"})",
     "legendFormat": "Largest Shard"
    }
   ]
  },
  {
   "title": "Top 3 Storage by Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (stream,date) (stream_date:elasticsearch_indices_store_size_bytes:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"}))",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "Top 3 Documents by Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (stream,date) (stream_date:elasticsearch_indices_docs_primary:sum{cluster=\"$esCluster\",stream=~\"$esIndex\"}))",
     "legendFormat": "{{date}}"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "ElasticSearch Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"elastic-$esCluster\",pod=~\"$esNode\",container!=\"\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ElasticSearch Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"elastic-logs\", pod=~\"$esNode\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ElasticSearch Node IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_filesystem_io_stats_device_operations_count{namespace=\"elastic-logs\", name=~\"$esNode\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ElasticSearch Node JVM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (elasticsearch_jvm_memory_pool_used_bytes{cluster=\"$esCluster\", name=~\"$esNode\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Node $esNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "esNode" },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "              max by (namespace, pod, container) (\n                rate(container_cpu_usage_seconds_total{namespace=\"elastic-$esCluster\",pod=~\"$esNode\",container!=\"\"}[2m])\n              ) /\n              (min by (namespace, pod, container) (\n                kube_pod_container_resource_limits{\n                  namespace=\"elastic-$esCluster\",\n                  resource=\"cpu\"\n                }) or min by (namespace, pod, container) (\n                kube_pod_container_resource_requests{\n                  namespace=\"elastic-$esCluster\",\n                  resource=\"cpu\"\n                }))\n            \n",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "              max by (namespace, pod, container) (\n                container_memory_working_set_bytes{\n                  namespace=\"elastic-$esCluster\",\n                  pod=~\"$esNode\",\n                  container!=\"\"\n                }\n              ) /\n              (min by (namespace, pod, container) (\n                kube_pod_container_resource_limits{\n                  namespace=\"elastic-$esCluster\",\n                  resource=\"memory\"\n                }) or min by (namespace, pod, container) (\n                kube_pod_container_resource_requests{\n                  namespace=\"elastic-$esCluster\",\n                  resource=\"memory\"\n                }))\n            \n",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "JVM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, cluster, name) (max_over_time(elasticsearch_jvm_memory_pool_used_bytes{cluster=\"$esCluster\",name=~\"$esNode\"}[5m])) / sum by (namespace, cluster, name) (min_over_time(elasticsearch_jvm_memory_pool_max_bytes{cluster=\"$esCluster\"}[2m]))",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_available_bytes{cluster=\"$esCluster\",name=~\"$esNode\"} / elasticsearch_filesystem_data_size_bytes",
     "legendFormat": "PVC"
    }
   ]
  },
  {
   "title": "IOPS Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, cluster, name) (ceil(rate(elasticsearch_filesystem_io_stats_device_operations_count{cluster=\"$esCluster\",name=~\"$esNode\"}[5m]))) / sum by (namespace, cluster, name) (45 * (elasticsearch_filesystem_data_size_bytes / (1024*1024*1024)))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_node_shards_total{cluster=\"$esCluster\",node=~\"$esNode\"}",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (namespace,cluster,node) (elasticsearch_node_shards_total{cluster=\"$esCluster\",node=~\"$esNode\"}) / min by (namespace,cluster,node) (label_replace(elasticsearch_jvm_memory_max_bytes{cluster=\"$esCluster\",name=~\"$esNode\",area=\"heap\"},\"node\", \"$1\", \"name\", \"(.*)\") / (1024^3))",
     "legendFormat": "per JVM GiB"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "name:elasticsearch_filesystem_data_free_bytes:capacity_by_top_indicies{cluster=\"$esCluster\",name=~\"$esNode\"}",
     "legendFormat": "Remaining Capacity"
    }
   ]
  }
 ]
}