---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema= https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json

# This is an empty Secret resource which Elastic will update with the required
# information needed during the operation of the deployed Elasticsearch
# service.
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elastic-logs
  annotations:
    eck.k8s.elastic.co/credentials: 'true'
type: Opaque
