---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema= https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
stringData:
  credentials.json: |-
    {
      "AccountTag":"${cloudflared_account_id}",
      "TunnelSecret":"${cloudflared_tunnel_secret}",
      "TunnelName":"${cloudflared_tunnel_name}",
      "TunnelID": "${cloudflared_tunnel_id}"
    }
