---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
stringData:
  credentials.json: |-
    {
      "AccountTag":"${cloudflared_account_id}",
      "TunnelSecret":"${cloudflared_tunnel_secret}",
      "TunnelName":"${cloudflared_tunnel_name}",
      "TunnelID": "${cloudflared_tunnel_id}"
    }
