---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
namespace: cloudflared-system

resources:
  - namespace.yaml
  - cloudflared-helm.yaml
  - cloudflared-secrets.yaml

commonLabels:
  flux.kub3.uk/organisation: n3tuk
  flux.kub3.uk/repository: infra-flux
  flux.kub3.uk/kustomization: cloudflared
  flux.kub3.uk/name: cloudflared
  flux.kub3.uk/application: cloudflared
  flux.kub3.uk/component: tunnel
  flux.kub3.uk/managed-by: kustomization

configMapGenerator:
  - name: helm-cloudflared-values
    files:
      - values.yaml=cloudflared-values.yaml

configurations:
  - kustomize-config.yaml
