---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: ingress-nginx
      chart: ingress-nginx
      interval: 5m
      version: 4.11.3
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-internal-values
