---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: internal

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/component: internal

resources:
  - ingress-nginx-helm.yaml

configMapGenerator:
  - name: helm-nginx-internal-values
    files:
      - values.yaml=ingress-nginx-values.yaml

configurations:
  - kustomize-config.yaml
