---
# Automatically update the reference to the ConfigMap containing the HelmRelease
# values, forcing the resource to reconcile on changes to the configuration
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: HelmRelease
        path: spec/valuesFrom/name
