---
apiVersion: v1
kind: Namespace
metadata:
  name: app-podinfo
  labels:
    app.kubernetes.io/environment: ${label_environment}
    app.kubernetes.io/instance: podinfo
    app.kubernetes.io/managed-by: Kustomization
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/repository: ${label_repository}
