---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/component: cert-manager

resources:
  - cert-manager-helm.yaml

configMapGenerator:
  - name: helm-cert-manager-values
    files:
      - values.yaml=cert-manager-values.yaml

configurations:
  - kustomize-config.yaml
