---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: kube-state-metrics
      flux.kub3.uk/name: prometheus
      flux.kub3.uk/application: kube-state-metrics
      flux.kub3.uk/component: metrics
      flux.kub3.uk/managed-by: kustomization

resources:
  - kube-state-metrics-helm.yaml
  - service-monitors.yaml

configMapGenerator:
  - name: helm-kube-state-metrics-values
    files:
      - values.yaml=kube-state-metrics-values.yaml

configurations:
  - kustomize-config.yaml
