---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: flux-community
      chart: flux2
      interval: 5m
      version: 2.14.1
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  test:
    enable: true
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-flux-values
