---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
namespace: flux-system

labels:
  - includeSelectors: false
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: flux
      flux.kub3.uk/name: flux
      flux.kub3.uk/application: flux
      flux.kub3.uk/component: flux
      flux.kub3.uk/managed-by: kustomization

resources:
  # Namespace already created during bootstrapping
  - flux-helm.yaml

configMapGenerator:
  - name: helm-flux-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=flux-values.yaml
