---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
spec:
  type: slack
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: notification-slack-token
  channel: kub3-${cluster}-flux
