---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-dns
  namespace: dns-system
  labels:
    alertmanager: metrics
spec:
  groups:
    - name: external-dns-updates
      rules:
        - alert: ExternalDNSLastReconcileWarning
          expr: |-
            ( time()
                -
              external_dns_controller_last_reconcile_timestamp_seconds
            ) * on (namespace, pod) group_left (node) (
              group by (node, namespace, pod) (
                kube_pod_info
              )
            ) > 3600
          for: 10m
          annotations:
            title: >-
              `external-dns` Not Reconciling
            summary: >-
              One or more of the `external-dns` `Pods` on the `{{$externalLabels.cluster}}` Cluster
              have not *reconciled the DNS entries between the Cluster and a DNS registry* for at
              least the last hour.
            description: >-
              `{{$labels.pod}}` `Pod` on the `Node` `{{$labels.node}}`
              (*{{$value|humanizeDuration}}*)
            runbook: https://d.n3t.uk/runbooks/
          labels:
            ignore: outside-extended-hours
            # severity can be info, errors, warning, critical
            severity: critical
            # slack is the name of the channel to send messages to
            slack: kub3-${cluster}-alerts-infra
            # pagerduty can either be send or ignore for Alerts
            pagerduty: send
            # incidentio can either create incidents, send Alerts, or ignore
            incidentio: create
            # team sets the Team and Escalation Path to use for the incident
            team: platform

        - alert: ExternalDNSSourceErrors
          expr: |-
            increase(
              external_dns_source_errors_total[1h]
            ) * on (namespace, pod) group_left (node) (
              group by (node, namespace, pod) (
                kube_pod_info
              )
            ) > 0
          for: 1m
          annotations:
            title: >-
              `external-dns` Source Errors
            summary: >-
              One or more of the `external-dns` `Pods` on the `{{$externalLabels.cluster}}` Cluster
              have reported *an increase in the errors collating resources and records from
              Kubernetes resources* within the last hour.
            description: >-
              `{{$labels.pod}}` `Pod` on the `Node` `{{$labels.node}}`
              (*{{$value|humanizeDuration}}*)
            runbook: https://d.n3t.uk/runbooks/
          labels:
            ignore: outside-extended-hours
            severity: critical
            slack: kub3-${cluster}-alerts-infra
            pagerduty: send
            incidentio: create
            team: platform

        - alert: ExternalDNSRegistryErrors
          expr: |-
            increase(
              external_dns_registry_errors_total[1h]
            ) * on (namespace, pod) group_left (node) (
              group by (node, namespace, pod) (
                kube_pod_info
              )
            ) > 0
          for: 1m
          annotations:
            title: >-
              `external-dns` Registry Errors
            summary: >-
              One or more of the `external-dns` `Pods` on the `{{$externalLabels.cluster}}` Cluster
              have reported *an increase in the errors requesting checks and updates against DNS
              registries Kubernetes resources* within the last hour.
            description: >-
              `{{$labels.pod}}` `Pod` on the `Node` `{{$labels.node}}`
              (*{{$value|humanizeDuration}}*)
            runbook: https://d.n3t.uk/runbooks/
          labels:
            ignore: outside-extended-hours
            severity: critical
            slack: kub3-${cluster}-alerts-infra
            pagerduty: send
            incidentio: create
            team: platform
