---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
namespace: app-github
resources:
  - namespace.yaml
  - controller-helm.yaml
  - runners-helm.yaml
configMapGenerator:
  - name: helm-controller-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=controller-values.yaml
  - name: helm-runners-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=runners-values.yaml
