---
apiVersion: v1
kind: Namespace
metadata:
  name: app-github
  labels:
    app.kubernetes.io/environment: ${label_environment}
    app.kubernetes.io/instance: github
    app.kubernetes.io/managed-by: Kustomization
    app.kubernetes.io/name: github
    app.kubernetes.io/repository: ${label_repository}
