---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
namespace: metallb-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: metallb
      flux.kub3.uk/name: metallb
      flux.kub3.uk/application: metallb
      flux.kub3.uk/component: metallb
      flux.kub3.uk/managed-by: kustomization

resources:
  - namespace.yaml
  - metallb-helm.yaml
  - prometheus-rules.yaml

configMapGenerator:
  - name: helm-metallb-values
    files:
      - values.yaml=metallb-values.yaml

configurations:
  - kustomize-config.yaml
