---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: metallb
      chart: metallb
      interval: 5m
      version: 0.15.2
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  test:
    enable: true
  driftDetection:
    # metallb seems to continuously reconcile the configuration, so disabling
    # until this can be investigated further
    mode: disabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-metallb-values
