---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cloudflare-staging
  namespace: cert-manager
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-staging
  secretName: letsencrypt-cloudflare-staging-tls
  privateKey:
    algorithm: RSA
    size: 4096
  dnsNames:
    - cloudflare.letsencrypt.certs.${cluster_domain}
