---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
namespace: kube-system

resources:
  - metrics-server-helm.yaml

commonLabels:
  flux.kub3.uk/organisation: n3tuk
  flux.kub3.uk/repository: infra-flux
  flux.kub3.uk/kustomization: metrics-server
  flux.kub3.uk/name: metrics-server
  flux.kub3.uk/application: metrics-server
  flux.kub3.uk/component: metrics-server
  flux.kub3.uk/managed-by: kustomization

configMapGenerator:
  - name: helm-metrics-server-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=metrics-server-values.yaml
