---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      flux.kub3.uk/organisation: n3tuk
      flux.kub3.uk/repository: infra-flux
      flux.kub3.uk/kustomization: metrics-server
      flux.kub3.uk/name: metrics-server
      flux.kub3.uk/application: metrics-server
      flux.kub3.uk/component: metrics-server
      flux.kub3.uk/managed-by: kustomization

resources:
  - metrics-server-helm.yaml

configMapGenerator:
  - name: helm-metrics-server-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=metrics-server-values.yaml
