---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: metrics-server
      chart: metrics-server
      interval: 5m
      version: 3.12.2
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  test:
    enable: true
  driftDetection:
    mode: enabled

  valuesFrom:
    - kind: ConfigMap
      name: helm-metrics-server-values
