---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit-deployment
  namespace: elastic-logs
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: fluent
      chart: fluent-bit
      interval: 5m
      version: 0.48.5
  interval: 3h
  install:
    crds: CreateReplace
    createNamespace: false
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  test:
    enable: true
  driftDetection:
    mode: enabled
  dependsOn:
    # Shared resources (e.g. the ServiceAccount) are created in the DaemonSet
    # deployment of fluent-bit, so ensure that is deployed and operational first
    - name: fluent-bit-daemonset

  valuesFrom:
    - kind: ConfigMap
      name: helm-fluent-bit-deployment-values
