---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema= https://github.com/yannh/kubernetes-json-schema/raw/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-credentials
  namespace: elastic-logs
  labels:
    app.kubernetes.io/managed-by: kustomization
stringData:
  password: ${elasticsearch_fluent_bit_password}
