---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-deployment
  namespace: elastic-logs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-deployment
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-deployment
subjects:
  - kind: ServiceAccount
    name: fluent-bit-deployment
    namespace: elastic-logs
