---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-credentials
  namespace: elastic-logs
  labels:
    app.kubernetes.io/managed-by: kustomization
stringData:
  password: ${elasticsearch_fluent_bit_password}
