---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluentbit
  namespace: flux-system
namespace: elastic-logs

commonLabels:
  flux.kub3.uk/organisation: n3tuk
  flux.kub3.uk/repository: infra-flux
  flux.kub3.uk/kustomization: fluentbit
  flux.kub3.uk/application: elastic-logs
  flux.kub3.uk/component: fluentbit

resources:
  # - fluent-bit-service-account.yaml
  - fluent-bit-secrets.yaml
  - fluent-bit-daemonset-helm.yaml
  - fluent-bit-deployment-helm.yaml

configMapGenerator:
  - name: helm-fluent-bit-daemonset-values
    files:
      - values.yaml=fluent-bit-daemonset-values.yaml
  - name: helm-fluent-bit-deployment-values
    files:
      - values.yaml=fluent-bit-deployment-values.yaml

configurations:
  - kustomize-config.yaml
