---
crds:
  enabled: true
  keep: true

replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 32Mi

topologySpreadConstraints:
  # With three Proxmox nodes and two workers per node, this will ensure that
  # cert-manager is distributed across multiple nodes, not just multiple workers
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: trust-manager
        app.kubernetes.io/instance: trust-manager
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: cert-manager-approver-policy
        app.kubernetes.io/instance: approver-policy

filterExpiredCertificates:
  enabled: true

app:
  logFormat: json

  webhook:
    tls:
      approverPolicy:
        enabled: true
        certManagerNamespace: cert-manager
        certManagerServiceAccount: cert-manager

  metrics:
    service:
      enabled: true
      servicemonitor:
        enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1
