---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-haproxy-ca
  namespace: certificates-system
spec:
  isCA: true
  commonName: ingress-haproxy Private Certificate Authority
  subject:
    organizations:
      - n3t.uk Lab Environment
    organizationalUnits:
      - n3tuk Kubernetes Certificate Authority
    provinces:
      - Bridgend
    localities:
      - Wales
    countries:
      - UK
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ingress-haproxy-root-ca-tls
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/main/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-haproxy-ca
spec:
  ca:
    issuingCertificateURLs:
      - http://ca.n3t.uk/haproxy/ca.crt
    crlDistributionPoints:
      - http://ca.n3t.uk/haproxy/ca.crl
    secretName: ingress-haproxy-root-ca-tls
